[versions]
agp = "8.12.1"
kotlin = "2.0.21"

commons-io = "2.20.0"
bouncycastle = "1.81"
guava = "33.4.8-jre"

appcompat = "1.8.0"
documentfile = "1.1.0"
core-ktx = "1.17.0"

[libraries]
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }

bouncycastle-bcpg = { group = "org.bouncycastle", name = "bcpg-jdk15to18", version.ref = "bouncycastle" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
